[project]
name = "onmibci-activatemask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "bleak>=1.1,<4",
    "mne>=1.6",
    "numpy>=1.24",
    "pyedflib>=0.1.39",
    "pyqtgraph>=0.13",
    "pyserial>=3.5",
    "pyside6>=6.5",
    "scipy>=1.10",
    "websockets>=14,<16",
]

[project.optional-dependencies]
export = [
    "mne>=1.6",
    "pyedflib>=0.1.39",
]

[[tool.uv.index]]
url = "https://mirrors.sustech.edu.cn/pypi/web/simple"
default = true
